Feat 355 add related projects
wizeline/project-lab pull request #369
Opened 2022-08-11 19:33 UTC by JCoronaWize

#### What does this PR do?
Adds the related projects Model
Includes select input to add related projects
Creates and Deletes relations between projects when updating projects in projects Page
Adds Related projects section in projects detail's page

#### Where should the reviewer start?
Check the created the new model: RelatedProjects on `schema.prisma`
Run the project a go to a projects **Edit Page** to view the new `related projects `field

#### How should this be manually tested?

1. Go to a projects edit Page.
2. Add projects on the `related projects `input, and save
3. On the **_Project's details_** page check that on **_Related Projects_** section the information is updated.

#### Any background context you want to provide?
This  a featured meant to allow users to see projects that are related to each other, which relation is created by the project members and/or admin users. 
This MVP is a feature that would be added to the projects new version using REMIX

#### What are the relevant tickets?
This is related to #355 

#### Screenshots
<img width="1495" alt="Captura de Pantalla 2022-08-11 a la(s) 14 27 31" src="https://user-images.githubusercontent.com/90728303/184223595-663024d7-feb4-48e6-8af8-2b8bac3c0a6d.png">

<img width="1450" alt="Captura de Pantalla 2022-08-11 a la(s) 14 28 21" src="https://user-images.githubusercontent.com/90728303/184223588-3d04358d-ff87-4cc5-bff4-bcab2c74bc81.png">

#### Questions
We could use other UI element instead of `Chips` if we wish to add more information.
Would this feature be added to other sections ? eg: `Admins Page`

2022-08-11 21:11 UTC, LuisTejedaS requested changes
just minor changes

2022-08-11 22:11 UTC, JCoronaWize commented on app/core/components/RelatedProjectsSelect/index.tsx
> +// import getSkills from "app/skills/queries/getSkills"
Sure thing

2022-08-11 22:54 UTC, LuisTejedaS approved these changes
There is still a commented line, you can either delete it and then merge or merge and then we just delete it

2022-08-12 00:12 UTC, JCoronaWize commented
Removed, thank you

2022-08-12 00:12 UTC, merged